FROM node:lts-alpine

WORKDIR /app

COPY . .

RUN npm install -g pnpm

RUN pnpm install --filter api

RUN pnpm add cors --filter api

RUN pnpm build --filter api

# 3333 -> 80
EXPOSE 3333:80

CMD ["node", "dist/index.js"]