FROM node:lts-alpine

WORKDIR /app

COPY . .

RUN npm install -g pnpm

RUN pnpm install

RUN pnpm build --filter api

# Define some ENV Vars
ENV PORT=3333 \
  DIRECTORY=/app \
  IS_DOCKER=true


CMD ["node", "dist/index.js"]

EXPOSE ${PORT}:80